from __future__ import annotations

LOW_RISK_TOOLS = {
    "browser.close_session",
    "browser.close_tab",
    "browser.extract_visible_text",
    "browser.get_active_session",
    "browser.get_page_info",
    "browser.go_back",
    "browser.go_forward",
    "browser.inspect_elements",
    "browser.inspect_clickable_elements",
    "browser.inspect_form_controls",
    "browser.input_text",
    "browser.clear_input",
    "browser.capture_view",
    "browser.list_tabs",
    "browser.open_url",
    "browser.open_new_tab",
    "browser.reload_page",
    "browser.scroll_page",
    "browser.scroll_to_element",
    "browser.start_session",
    "browser.switch_tab",
    "browser.take_screenshot",
    "browser.wait_for_page",
    "vision.describe_image",
    "vision.describe_browser_capture",
    "vision.describe_desktop_capture",
    "vision.extract_text",
    "vision.extract_text_from_browser_capture",
    "vision.extract_text_from_desktop_capture",
    "vision.find_visual_element",
    "vision.find_visual_element_in_browser_capture",
    "vision.find_visual_element_in_desktop_capture",
    "desktop.list_windows",
    "calculator.calculate",
    "computer.open_application",
    "computer.open_known_folder",
    "filesystem.append_text_file",
    "filesystem.copy_path",
    "filesystem.create_directory",
    "filesystem.create_text_file",
    "filesystem.exists",
    "filesystem.list_directory",
    "filesystem.metadata",
    "filesystem.move_path",
    "filesystem.read_text_file",
    "filesystem.rename_path",
    "filesystem.write_text_file",
    "internet.search",
    "memory.recall",
    "notes.list",
    "system.get_date",
    "system.get_time",
    "system.system_info",
    "tasks.list",
}

MEDIUM_RISK_TOOLS = {
    "desktop.capture_screen",
    "desktop.capture_window",
    "filesystem.delete_path",
    "memory.forget",
    "memory.remember",
    "notes.create",
    "tasks.create",
}

HIGH_RISK_PREFIXES = (
    "browser.download",
    "browser.publish",
    "config.",
    "package.",
    "plugin.",
)

HIGH_RISK_TOOLS = {
    "power.request_lock",
    "power.request_restart",
    "power.request_shutdown",
}
