from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
APP_NAME = "JARVIS"
VERSION = "2.5.0"
LOG_LEVEL = "INFO"
LOG_FILE = BASE_DIR / "logs" / "jarvis.log"
DEFAULT_SETTINGS = {
    "assistant_name": APP_NAME,
    "language": "en",
    "voice_enabled": True,
    "logging_enabled": True,
    "theme": "dark",
    "startup_message": "Hello",
    "ai_enabled": True,
    "ai_provider": "ollama",
    "ollama_base_url": "http://127.0.0.1:11434",
    "ollama_model": "llama3.2",
    "ai_timeout_seconds": 20,
    "ai_max_plan_steps": 5,
    "ai_max_response_chars": 12000,
    "ai_allow_conversation": True,
    "show_plan_preview": True,
    "agent_enabled": True,
    "agent_max_steps": 10,
    "agent_result_size_limit": 200,
    "agent_allow_persistent_actions": True,
    "filesystem_enabled": True,
    "filesystem_max_file_size": 1048576,
    "filesystem_max_read_size": 65536,
    "filesystem_max_write_size": 65536,
    "filesystem_soft_delete": True,
    # Owner's explicit choice (2026-09-19 boundary discussion): give JARVIS's filesystem
    # and terminal tools access to the whole system drive, not just its own project
    # folder, so it can act on real files (Desktop, Documents, Downloads, ...). Default
    # False -- a fresh install/other user opts in deliberately, since this is a real
    # widening of what a local AI model can touch. See
    # app/brain/filesystem/path_policy.py's is_forbidden_system_location() for what stays
    # off limits even when this is on (Windows/Program Files/System32, and any OTHER
    # account's Users\<name> profile).
    "filesystem_allow_full_disk_access": False,
    "developer_mode": False,
    "auto_execute_low_risk": True,
    "auto_execute_medium_project": True,
    "terminal_enabled": True,
    "terminal_default_working_directory": str(BASE_DIR),
    "terminal_timeout_seconds": 30,
    "terminal_max_stdout_chars": 20000,
    "terminal_max_stderr_chars": 20000,
    "terminal_history_limit": 25,
    "terminal_allow_python": True,
    "terminal_allow_git_read_only": True,
    "terminal_allow_package_install_with_approval": True,
    "browser_enabled": True,
    "browser_backend": "playwright",
    "browser_headless_default": True,
    "browser_navigation_timeout_seconds": 30,
    "browser_extract_text_max_chars": 4000,
    "browser_max_elements": 40,
    "browser_allow_http": False,
    "browser_screenshot_overwrite": False,
    "vision_enabled": True,
    "vision_provider": "ollama",
    "vision_model": "",
    "vision_ollama_base_url": "http://127.0.0.1:11434",
    "vision_timeout_seconds": 90,
    "vision_max_file_size": 4194304,
    "vision_max_width": 4096,
    "vision_max_height": 4096,
    "vision_max_pixels": 4194304,
    "vision_max_ocr_chars": 4000,
    "vision_max_regions": 8,
    "vision_evidence_retention_seconds": 300,
    "vision_browser_capture_enabled": True,
    "vision_browser_capture_ttl_seconds": 180,
    "vision_browser_capture_max_bytes": 2_000_000,
    "vision_browser_capture_max_width": 1920,
    "vision_browser_capture_max_height": 1080,
    "vision_browser_capture_max_pixels": 2_073_600,
    "vision_browser_capture_min_candidate_width_pixels": 12,
    "vision_browser_capture_min_candidate_height_pixels": 12,
    "vision_browser_capture_min_candidate_area_pixels": 144,
    "vision_browser_capture_verification_context_scale_percent": 400,
    "vision_browser_capture_verification_context_min_width_pixels": 320,
    "vision_browser_capture_verification_context_min_height_pixels": 320,
    "vision_browser_capture_verification_context_max_area_percent": 40,
    "intelligence_enabled": True,
    "intelligence_provider": "ollama",
    "intelligence_model": "llama3.2",
    "intelligence_timeout_seconds": 60,
    "intelligence_max_plan_steps": 10,
    "intelligence_max_context_chars": 30000,
    "intelligence_max_recent_messages": 12,
    "intelligence_require_structured_output": True,
    "intelligence_allow_goal_evaluation": True,
    "intelligence_allow_heuristic_fallback": False,
    "intelligence_fail_closed": True,
    "intelligence_max_planning_attempts": 2,
    "memory_max_entries": 500,
    "memory_learned_capture_enabled": True,
    "vision_desktop_capture_enabled": True,
    "vision_desktop_capture_ttl_seconds": 180,
    "vision_desktop_capture_max_bytes": 6_000_000,
    "vision_desktop_capture_max_width": 3840,
    "vision_desktop_capture_max_height": 2160,
    "vision_desktop_capture_max_pixels": 8_294_400,
    "location_enabled": False,
    "location_bind_host": "",
    "location_port": 8766,
    "location_shared_secret": "",
    "location_stale_after_seconds": 120,
    "osrm_base_url": "http://router.project-osrm.org",
    "voice_stt_model": "small",
    "voice_tts_voice": "",
    "voice_require_speaker_verification": False,
    "voice_verification_threshold": 0.4,
    "voice_input_device": 1,
    "voice_input_sample_rate": 44100,
    "voice_input_channels": 4,
    "voice_talk_auto_stop_on_silence": True,
    "voice_talk_silence_timeout_seconds": 1.0,
    "voice_talk_min_duration_seconds": 1.0,
    "voice_listen_on_startup": True,
    "plan_approval_timeout_seconds": 60,
    "max_conversation_entries": 20,
    "max_timeline_entries": 100,
    "max_persistent_writes_per_plan": 2,
    "max_external_actions_per_plan": 2,
    "plugins_enabled": True,
    "enabled_plugin_ids": ["example_plugin"],
}
